name: Quick HTML to APK

on:
  push:
    branches: [ "main" ]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Convert to APK
      uses: tttstudios/html-to-apk-action@v1
      with:
        app-name: "MyQuickApp"
        package-name: "com.quickapk.app"
        icon-path: "" # Isko khali rehne dein default icon ke liye

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app-apk
        path: ./*.apk
